// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoastHiveMvc.Data;

#nullable disable

namespace RoastHiveMvc.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20230516153853_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("RoastHiveMvc.Models.Product", b =>
                {
                    b.Property<int>("prodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("catId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("unitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("prodID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
